const optionSets = [
  {
    id: 'opt-symptoms-dental',
    key: 'symptoms_dental',
    name: 'Dental Symptoms',
    category: 'symptoms',
    visibility: 'system',
    items: [
      'Tooth pain',
      'Sensitivity',
      'Gum swelling',
      'Bleeding gums',
      'Bad breath',
      'Difficulty chewing',
    ],
  },
  {
    id: 'opt-symptoms-general',
    key: 'symptoms_general',
    name: 'General Symptoms',
    category: 'symptoms',
    visibility: 'system',
    items: [
      'Fever',
      'Cough',
      'Sore throat',
      'Body ache',
      'Fatigue',
      'Headache',
    ],
  },
  {
    id: 'opt-medicines',
    key: 'common_medicines',
    name: 'Common Medicines',
    category: 'medicines',
    visibility: 'hospital',
    items: [
      'Amoxicillin 500mg',
      'Ibuprofen 400mg',
      'Paracetamol 650mg',
      'Cetirizine 10mg',
      'Pantoprazole 40mg',
      'Chlorhexidine mouthwash',
    ],
  },
  {
    id: 'opt-advice-dental',
    key: 'dental_advice',
    name: 'Dental Advice Library',
    category: 'advice',
    visibility: 'hospital',
    items: [
      'Avoid hot and cold food for 24 hours',
      'Do not chew from the treated side',
      'Use warm saline rinses twice daily',
      'Brush gently around the affected area',
      'Return immediately if swelling increases',
    ],
  },
  {
    id: 'opt-follow-up',
    key: 'follow_up_window',
    name: 'Follow Up Windows',
    category: 'follow_up',
    visibility: 'system',
    items: ['24 hours', '3 days', '5 days', '1 week', '2 weeks'],
  },
]

const templates = [
  {
    id: 'tpl-dental-exam',
    key: 'dental_exam_plus',
    name: 'Dental Exam Plus',
    visibility: 'system',
    specialty: 'Dental',
    description: 'Balanced template for consultation, procedures, medicines, and after-care.',
    ownerLabel: 'System starter',
    isDefault: true,
    sectionCount: 5,
    fieldCount: 14,
    presetCount: 2,
    sections: [
      {
        id: 'sec-visit-overview',
        key: 'visit_overview',
        title: 'Visit Overview',
        description: 'Core clinical details that should stay on almost every prescription.',
        isRequired: true,
        isRemovable: false,
        columns: 2,
        fields: [
          {
            id: 'fld-chief-complaint',
            key: 'chiefComplaint',
            label: 'Chief complaint',
            type: 'textarea',
            required: true,
            locked: true,
            removable: false,
            width: 2,
            placeholder: 'Patient states the main issue in a single concise line.',
          },
          {
            id: 'fld-symptoms',
            key: 'symptoms',
            label: 'Symptoms',
            type: 'multi_select',
            required: false,
            locked: false,
            removable: true,
            width: 2,
            optionSetKey: 'symptoms_dental',
          },
          {
            id: 'fld-diagnosis',
            key: 'diagnosis',
            label: 'Diagnosis',
            type: 'text',
            required: true,
            locked: true,
            removable: false,
            width: 1,
            placeholder: 'Acute pulpitis / Gingivitis / Post extraction review',
          },
          {
            id: 'fld-procedure',
            key: 'procedurePerformed',
            label: 'Procedure performed',
            type: 'text',
            required: false,
            locked: false,
            removable: true,
            width: 1,
            placeholder: 'Scaling / RCT access opening / Extraction',
          },
        ],
      },
      {
        id: 'sec-exam',
        key: 'clinical_exam',
        title: 'Clinical Exam',
        description: 'Compact findings to keep the screen useful without extra scroll.',
        isRequired: false,
        isRemovable: true,
        columns: 2,
        fields: [
          {
            id: 'fld-bp',
            key: 'bloodPressure',
            label: 'Blood pressure',
            type: 'text',
            width: 1,
            placeholder: '120/80 mmHg',
          },
          {
            id: 'fld-temp',
            key: 'temperature',
            label: 'Temperature',
            type: 'text',
            width: 1,
            placeholder: '98.6 F',
          },
          {
            id: 'fld-oral-findings',
            key: 'oralFindings',
            label: 'Oral findings',
            type: 'textarea',
            width: 2,
            placeholder: 'Localized tenderness, distal caries, mild swelling.',
          },
        ],
      },
      {
        id: 'sec-medications',
        key: 'medications',
        title: 'Medications',
        description: 'Fast reusable medicine panel with structured rows.',
        isRequired: true,
        isRemovable: false,
        columns: 1,
        fields: [
          {
            id: 'fld-medications',
            key: 'medications',
            label: 'Medication list',
            type: 'medication_list',
            required: true,
            locked: true,
            removable: false,
            width: 1,
          },
        ],
      },
      {
        id: 'sec-advice',
        key: 'advice',
        title: 'Advice & Cautions',
        description: 'Frequently reused instructions that the doctor can customize quickly.',
        isRequired: true,
        isRemovable: false,
        columns: 1,
        fields: [
          {
            id: 'fld-advice',
            key: 'advice',
            label: 'Advice',
            type: 'multi_select',
            required: true,
            locked: false,
            removable: true,
            width: 1,
            optionSetKey: 'dental_advice',
          },
        ],
      },
      {
        id: 'sec-followup',
        key: 'follow_up',
        title: 'Follow Up',
        description: 'Follow up window and clinician note.',
        isRequired: false,
        isRemovable: true,
        columns: 2,
        fields: [
          {
            id: 'fld-follow-up',
            key: 'followUpWindow',
            label: 'Follow up',
            type: 'select',
            width: 1,
            optionSetKey: 'follow_up_window',
            placeholder: 'Select timeline',
          },
          {
            id: 'fld-review-date',
            key: 'reviewDate',
            label: 'Review date',
            type: 'date',
            width: 1,
          },
          {
            id: 'fld-notes',
            key: 'clinicalNotes',
            label: 'Clinical notes',
            type: 'textarea',
            width: 2,
            placeholder: 'Notes for record, caution, or future procedure planning.',
          },
        ],
      },
    ],
  },
  {
    id: 'tpl-hospital-opd',
    key: 'hospital_opd_shared',
    name: 'Hospital Shared OPD',
    visibility: 'hospital',
    specialty: 'General OPD',
    description: 'Shared cross-specialty template that other doctors in the hospital can reuse.',
    ownerLabel: 'Hospital library',
    isDefault: false,
    sectionCount: 4,
    fieldCount: 12,
    presetCount: 1,
    sections: [
      {
        id: 'sec-opd-history',
        key: 'history',
        title: 'History',
        description: 'Symptoms, duration, and relevant history.',
        isRequired: true,
        isRemovable: false,
        columns: 2,
        fields: [
          {
            id: 'fld-opd-chief',
            key: 'chiefComplaint',
            label: 'Chief complaint',
            type: 'textarea',
            required: true,
            locked: true,
            removable: false,
            width: 2,
          },
          {
            id: 'fld-opd-duration',
            key: 'duration',
            label: 'Duration',
            type: 'text',
            width: 1,
            placeholder: '3 days / 1 week',
          },
          {
            id: 'fld-opd-symptoms',
            key: 'symptoms',
            label: 'Symptoms',
            type: 'multi_select',
            width: 1,
            optionSetKey: 'symptoms_general',
          },
        ],
      },
      {
        id: 'sec-opd-vitals',
        key: 'vitals',
        title: 'Vitals',
        description: 'Compact vital capture.',
        isRequired: false,
        isRemovable: true,
        columns: 2,
        fields: [
          { id: 'fld-opd-bp', key: 'bloodPressure', label: 'Blood pressure', type: 'text', width: 1 },
          { id: 'fld-opd-pulse', key: 'pulse', label: 'Pulse', type: 'text', width: 1 },
          { id: 'fld-opd-temp', key: 'temperature', label: 'Temperature', type: 'text', width: 1 },
          { id: 'fld-opd-spo2', key: 'spo2', label: 'SpO2', type: 'text', width: 1 },
        ],
      },
      {
        id: 'sec-opd-plan',
        key: 'plan',
        title: 'Assessment & Plan',
        description: 'Diagnosis, medicines, and advice.',
        isRequired: true,
        isRemovable: false,
        columns: 2,
        fields: [
          {
            id: 'fld-opd-diagnosis',
            key: 'diagnosis',
            label: 'Diagnosis',
            type: 'text',
            required: true,
            locked: true,
            removable: false,
            width: 1,
          },
          {
            id: 'fld-opd-followup',
            key: 'followUpWindow',
            label: 'Follow up',
            type: 'select',
            width: 1,
            optionSetKey: 'follow_up_window',
          },
          {
            id: 'fld-opd-medications',
            key: 'medications',
            label: 'Medication list',
            type: 'medication_list',
            required: true,
            locked: true,
            removable: false,
            width: 2,
          },
          {
            id: 'fld-opd-notes',
            key: 'clinicalNotes',
            label: 'Advice / Notes',
            type: 'textarea',
            width: 2,
          },
        ],
      },
    ],
  },
  {
    id: 'tpl-general-consultation-full',
    key: 'general_consultation_full',
    name: 'General Consultation (Full)',
    visibility: 'system',
    specialty: 'General OPD',
    description: 'Comprehensive multi-section template aligned to full clinical notes.',
    ownerLabel: 'System starter',
    isDefault: false,
    sectionCount: 10,
    fieldCount: 27,
    presetCount: 0,
    sections: [
      {
        id: 'sec-gen-vitals',
        key: 'vitals',
        title: 'Vitals',
        description: 'Core vitals at the time of visit.',
        isRequired: false,
        isRemovable: true,
        columns: 3,
        fields: [
          { id: 'fld-vital-temp', key: 'temperature', label: 'Temperature', type: 'text', width: 1, placeholder: '101 F' },
          { id: 'fld-vital-bp', key: 'bloodPressure', label: 'Blood pressure', type: 'text', width: 1, placeholder: '120/80' },
          { id: 'fld-vital-pulse', key: 'pulse', label: 'Pulse', type: 'text', width: 1, placeholder: '90 bpm' },
        ],
      },
      {
        id: 'sec-gen-complaints',
        key: 'complaints',
        title: 'Complaints',
        description: 'Symptoms and duration in patient words.',
        isRequired: true,
        isRemovable: false,
        columns: 2,
        fields: [
          {
            id: 'fld-complaints-list',
            key: 'complaints',
            label: 'Complaints',
            type: 'textarea',
            required: true,
            locked: true,
            removable: false,
            width: 2,
            placeholder: 'Fever - 2 days\nCough - 2 days',
          },
          {
            id: 'fld-complaints-duration',
            key: 'complaintsDuration',
            label: 'Overall duration',
            type: 'text',
            width: 1,
            placeholder: '2 days',
          },
        ],
      },
      {
        id: 'sec-gen-history',
        key: 'medical_history',
        title: 'Medical History',
        description: 'Relevant past history and current medications.',
        isRequired: false,
        isRemovable: true,
        columns: 2,
        fields: [
          {
            id: 'fld-history-medical',
            key: 'medicalHistory',
            label: 'Medical history',
            type: 'textarea',
            width: 2,
            placeholder: 'No prior chronic illness',
          },
          {
            id: 'fld-history-current-meds',
            key: 'currentMedications',
            label: 'Current medications',
            type: 'textarea',
            width: 2,
            placeholder: 'List ongoing medicines or write "None"',
          },
        ],
      },
      {
        id: 'sec-gen-hpi',
        key: 'history_present_illness',
        title: 'History of Present Illness',
        description: 'Chronological narrative of symptoms.',
        isRequired: false,
        isRemovable: true,
        columns: 1,
        fields: [
          {
            id: 'fld-hpi-summary',
            key: 'historyPresentIllness',
            label: 'HPI summary',
            type: 'textarea',
            width: 1,
            placeholder: 'Patient reports fever and cough since 2 days.',
          },
        ],
      },
      {
        id: 'sec-gen-exam',
        key: 'examination_findings',
        title: 'Examination Findings',
        description: 'Clinical findings and notes.',
        isRequired: false,
        isRemovable: true,
        columns: 2,
        fields: [
          {
            id: 'fld-exam-general',
            key: 'examGeneralCondition',
            label: 'General condition',
            type: 'text',
            width: 1,
            placeholder: 'Mild weakness',
          },
          {
            id: 'fld-exam-throat',
            key: 'examThroat',
            label: 'Throat',
            type: 'text',
            width: 1,
            placeholder: 'Slight redness',
          },
          {
            id: 'fld-exam-chest',
            key: 'examChest',
            label: 'Chest',
            type: 'text',
            width: 1,
            placeholder: 'Clear',
          },
          {
            id: 'fld-exam-notes',
            key: 'examNotes',
            label: 'Additional findings',
            type: 'textarea',
            width: 2,
            placeholder: 'Patient looks stable but weak',
          },
        ],
      },
      {
        id: 'sec-gen-advice',
        key: 'advice',
        title: 'Advice',
        description: 'Instructions and self-care guidance.',
        isRequired: false,
        isRemovable: true,
        columns: 1,
        fields: [
          {
            id: 'fld-advice-list',
            key: 'advice',
            label: 'Advice',
            type: 'textarea',
            width: 1,
            placeholder: 'Take rest\nDrink warm fluids\nAvoid cold items',
          },
          {
            id: 'fld-advice-notes',
            key: 'adviceNotes',
            label: 'Advice notes',
            type: 'textarea',
            width: 1,
            placeholder: 'Hydration is important',
          },
        ],
      },
      {
        id: 'sec-gen-treatment',
        key: 'treatment',
        title: 'Treatment',
        description: 'Treatment plan and notes.',
        isRequired: false,
        isRemovable: true,
        columns: 1,
        fields: [
          {
            id: 'fld-treatment-list',
            key: 'treatment',
            label: 'Treatment',
            type: 'textarea',
            width: 1,
            placeholder: 'Symptomatic treatment',
          },
          {
            id: 'fld-treatment-notes',
            key: 'treatmentNotes',
            label: 'Treatment notes',
            type: 'textarea',
            width: 1,
            placeholder: 'No aggressive treatment required',
          },
        ],
      },
      {
        id: 'sec-gen-investigations',
        key: 'investigations',
        title: 'Investigations',
        description: 'Tests or diagnostics to consider.',
        isRequired: false,
        isRemovable: true,
        columns: 1,
        fields: [
          {
            id: 'fld-investigations-list',
            key: 'investigations',
            label: 'Investigations',
            type: 'textarea',
            width: 1,
            placeholder: 'CBC if fever persists',
          },
          {
            id: 'fld-investigations-notes',
            key: 'investigationNotes',
            label: 'Investigation notes',
            type: 'textarea',
            width: 1,
            placeholder: 'Optional if no improvement',
          },
        ],
      },
      {
        id: 'sec-gen-medications',
        key: 'prescribed_medicines',
        title: 'Prescribed Medicines',
        description: 'Structured medicine list with dosage and timing.',
        isRequired: true,
        isRemovable: false,
        columns: 1,
        fields: [
          {
            id: 'fld-medications',
            key: 'medications',
            label: 'Medication list',
            type: 'medication_list',
            required: true,
            locked: true,
            removable: false,
            width: 1,
          },
        ],
      },
      {
        id: 'sec-gen-notes-followup',
        key: 'notes_followup',
        title: 'Precautions, Notes & Follow Up',
        description: 'Precautions, additional notes, and follow-up.',
        isRequired: false,
        isRemovable: true,
        columns: 2,
        fields: [
          {
            id: 'fld-precautions',
            key: 'precautions',
            label: 'Precautions',
            type: 'textarea',
            width: 2,
            placeholder: 'Avoid cold drinks\nWear warm clothes',
          },
          {
            id: 'fld-additional-notes',
            key: 'additionalNotes',
            label: 'Additional notes',
            type: 'textarea',
            width: 2,
            placeholder: 'Follow up if symptoms worsen',
          },
          {
            id: 'fld-deleterious-habits',
            key: 'deleteriousHabits',
            label: 'Deleterious habits',
            type: 'textarea',
            width: 1,
            placeholder: 'Smoking, alcohol, tobacco chewing',
          },
          {
            id: 'fld-file-links',
            key: 'fileLinks',
            label: 'File links',
            type: 'textarea',
            width: 1,
            placeholder: 'Paste file URLs, one per line',
          },
          {
            id: 'fld-follow-up-date',
            key: 'followUpDate',
            label: 'Follow up date',
            type: 'date',
            width: 1,
          },
        ],
      },
    ],
  },
  {
    id: 'tpl-dentist-custom',
    key: 'post_procedure_review',
    name: 'Post Procedure Review',
    visibility: 'doctor',
    specialty: 'Dental',
    description: 'Doctor-customized short template focused on review visits with minimal typing.',
    ownerLabel: 'Personal template',
    isDefault: false,
    sectionCount: 3,
    fieldCount: 8,
    presetCount: 2,
    sections: [
      {
        id: 'sec-custom-review',
        key: 'review',
        title: 'Review Summary',
        description: 'Fast review-focused structure.',
        isRequired: true,
        isRemovable: false,
        columns: 2,
        fields: [
          {
            id: 'fld-custom-condition',
            key: 'currentCondition',
            label: 'Current condition',
            type: 'textarea',
            required: true,
            locked: true,
            removable: false,
            width: 2,
          },
          {
            id: 'fld-custom-healing',
            key: 'healingStatus',
            label: 'Healing status',
            type: 'select',
            width: 1,
            options: ['Satisfactory', 'Needs observation', 'Requires intervention'],
          },
          {
            id: 'fld-custom-pain',
            key: 'painScore',
            label: 'Pain score',
            type: 'select',
            width: 1,
            options: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
          },
        ],
      },
      {
        id: 'sec-custom-medications',
        key: 'review_medications',
        title: 'Medicines & Advice',
        description: 'Medication refill plus advice.',
        isRequired: true,
        isRemovable: false,
        columns: 1,
        fields: [
          {
            id: 'fld-custom-medications',
            key: 'medications',
            label: 'Medication list',
            type: 'medication_list',
            required: true,
            locked: true,
            removable: false,
            width: 1,
          },
          {
            id: 'fld-custom-advice',
            key: 'advice',
            label: 'Advice',
            type: 'multi_select',
            width: 1,
            optionSetKey: 'dental_advice',
          },
        ],
      },
      {
        id: 'sec-custom-next',
        key: 'next_visit',
        title: 'Next Visit',
        description: 'Short planning block.',
        isRequired: false,
        isRemovable: true,
        columns: 2,
        fields: [
          {
            id: 'fld-custom-review-date',
            key: 'reviewDate',
            label: 'Review date',
            type: 'date',
            width: 1,
          },
          {
            id: 'fld-custom-urgent',
            key: 'urgentReview',
            label: 'Urgent review needed',
            type: 'switch',
            width: 1,
            defaultValue: false,
          },
          {
            id: 'fld-custom-notes',
            key: 'clinicalNotes',
            label: 'Notes',
            type: 'textarea',
            width: 2,
          },
        ],
      },
    ],
  },
]

const presets = [
  {
    id: 'preset-cold',
    templateId: 'tpl-hospital-opd',
    name: 'Common Cold',
    visibility: 'hospital',
    description: 'Shared quick-start preset for fever, cough, and sore throat cases.',
    values: {
      chiefComplaint: 'Cold, throat irritation, and mild fever since 3 days.',
      symptoms: ['Fever', 'Cough', 'Sore throat', 'Fatigue'],
      diagnosis: 'Upper respiratory tract infection',
      followUpWindow: '3 days',
      clinicalNotes: 'Hydration, steam inhalation, rest, and symptom review if fever persists.',
      medications: [
        {
          medicine: 'Paracetamol 650mg',
          dosage: '1 tablet',
          frequency: 'SOS',
          duration: '3 days',
          instructions: 'After food if fever > 100 F',
        },
        {
          medicine: 'Cetirizine 10mg',
          dosage: '1 tablet',
          frequency: 'HS',
          duration: '5 days',
          instructions: 'For throat irritation / sneezing',
        },
      ],
    },
  },
  {
    id: 'preset-extraction',
    templateId: 'tpl-dental-exam',
    name: 'Post Extraction Care',
    visibility: 'doctor',
    description: 'Used after extraction or minor oral surgery.',
    values: {
      chiefComplaint: 'Post extraction review with mild pain at the operated site.',
      diagnosis: 'Post extraction healing review',
      procedurePerformed: 'Extraction follow-up',
      advice: [
        'Avoid hot and cold food for 24 hours',
        'Do not chew from the treated side',
        'Use warm saline rinses twice daily',
      ],
      followUpWindow: '5 days',
      medications: [
        {
          medicine: 'Ibuprofen 400mg',
          dosage: '1 tablet',
          frequency: 'BD',
          duration: '3 days',
          instructions: 'After meals',
        },
        {
          medicine: 'Chlorhexidine mouthwash',
          dosage: '10 ml',
          frequency: 'BD',
          duration: '5 days',
          instructions: 'Rinse gently, do not swallow',
        },
      ],
    },
  },
  {
    id: 'preset-rct-review',
    templateId: 'tpl-dentist-custom',
    name: 'RCT Review Visit',
    visibility: 'doctor',
    description: 'Short review template with healing and pain tracking.',
    values: {
      currentCondition: 'Pain reduced significantly after previous visit. Mild tenderness on biting.',
      healingStatus: 'Satisfactory',
      painScore: '2',
      advice: ['Do not chew from the treated side', 'Return immediately if swelling increases'],
      reviewDate: '',
      clinicalNotes: 'Continue review till obturation visit.',
      medications: [
        {
          medicine: 'Ibuprofen 400mg',
          dosage: '1 tablet',
          frequency: 'BD',
          duration: '2 days',
          instructions: 'Only if pain persists',
        },
      ],
    },
  },
]

const architecture = [
  {
    name: 'prescription_templates',
    purpose: 'Template identity, ownership, sharing scope, and current version pointer.',
  },
  {
    name: 'prescription_template_versions',
    purpose: 'Immutable template versions so old prescriptions never break when a doctor edits the layout.',
  },
  {
    name: 'prescription_template_sections',
    purpose: 'Section-level grouping for compact UI layouts and removal rules.',
  },
  {
    name: 'prescription_template_fields',
    purpose: 'Dynamic field definitions with validation, UI config, repeatability, and option bindings.',
  },
  {
    name: 'prescription_option_sets / prescription_option_items',
    purpose: 'Reusable dropdown and suggestion libraries for medicines, cautions, symptoms, and follow-up windows.',
  },
  {
    name: 'prescription_presets / prescription_preset_values',
    purpose: 'Common-case reusable presets like cold, extraction review, or neurology follow-up.',
  },
  {
    name: 'prescriptions / prescription_values',
    purpose: 'Template-backed prescription instances with field values and a snapshot of the version used.',
  },
]

function clone(value) {
  return JSON.parse(JSON.stringify(value))
}

export function getPrescriptionTemplateCatalog() {
  return {
    templates: clone(templates),
    optionSets: clone(optionSets),
    presets: clone(presets),
    architecture: clone(architecture),
  }
}

export function getPrescriptionTemplateById(templateId) {
  return clone(templates.find((template) => template.id === templateId) || templates[0])
}

export function getPrescriptionOptionSetMap() {
  return optionSets.reduce((map, optionSet) => {
    map[optionSet.key] = optionSet.items
    return map
  }, {})
}

export function getRecommendedTemplateId(specialization = '') {
  const normalized = specialization.toLowerCase()

  if (normalized.includes('dental') || normalized.includes('dentist')) {
    return 'tpl-dental-exam'
  }

  return 'tpl-hospital-opd'
}

export function getPresetsForTemplate(templateId) {
  return clone(presets.filter((preset) => preset.templateId === templateId))
}
